#!/bin/sh
set -eu
cd ~/gh/self
git add nix
export NIX_CONF_DIR=~/gh/self/nix
hostname=${1?hostname empty}
# todo look in nix/hosts to find all available ones
# maybe just use $HOSTNAME duh?

# curl -s 'https://prometheus.nixos.org/api/v1/query?query=channel_revision' | jq -r '.data.result[].metric | select(.status == "stable" and .variant == "primary") | .channel'

nix run home-manager/release-23.11 -- switch --flake nix/#smart-toaster
