#!/bin/sh
set -eu
cd ~/gh/self
git add nix
hostname=${1?hostname empty}
# todo look in nix/hosts to find all available ones
# maybe just use $HOSTNAME duh?

# curl -s 'https://prometheus.nixos.org/api/v1/query?query=channel_revision' | jq -r '.data.result[].metric | select(.status == "stable" and .variant == "primary") | .channel'

export NIX_CONF_DIR=~/gh/self/nix

if command -v home-manager >/dev/null; then
        home-manager switch --flake nix/#smart-toaster
else
        echo "home-manager is not installed"
        nix run home-manager -- switch --flake nix/#smart-toaster
fi
