-- vim.g.tpipeline_usepane = 1
-- vim.g.tpipeline_fillcentre = 1
-- vim.g.tpipeline_autoembed = 0
-- vim.g.tpipeline_statusline = "%f"

-- config = function()
--   vim.notify("hi")
--   -- vim.g.tpipeline_tabline = 0
--   -- vim.g.tpipeline_focuslost = 0
--   -- -- vim.g.tpipeline_clearstl = 1
--   -- -- vim.g.tpipeline_split = 1
--   -- vim.g.tpipeline_restore = 1
--   -- vim.g.tpipeline_size = 500
--   -- vim.opt.laststatus = 0
--   --vim.g.tpipeline_split = 1
--
-- vim.g.tpipeline_embedopts = { "status-justify absolute-centre" }
-- vim.g.tpipeline_tabline = 0
-- vim.g.tpipeline_restore = 0
-- vim.g.tpipeline_focuslost = 0
-- vim.g.tpipeline_size = 500

-- vim.g.tpipeline_statusline = "#[bg=default]"
-- vim.g.tpipeline_statusline = vim.g.tpipeline_statusline .. ""
-- vim.g.tpipeline_statusline = vim.g.tpipeline_statusline .. "#[fg=brightcyan]%t%h%w%m%r " -- " %F
-- vim.g.tpipeline_statusline = vim.g.tpipeline_statusline .. "#[fg=orange](%l,%c%V) %P "
-- vim.g.tpipeline_statusline = vim.g.tpipeline_statusline .. "%="
-- vim.g.tpipeline_statusline = vim.g.tpipeline_statusline .. "#[fg=brightmagenta]%y"
-- vim.g.tpipeline_statusline = vim.g.tpipeline_statusline
--   .. "#[fg=pink][%{&fileformat} %{&fileencoding?&fileencoding:&encoding}]"
--
