{
  pkgs,
  lib,
  host,
  ...
}:

{
  home.packages = with pkgs; [ tmux ];

  xdg.configFile."tmux" = host.symlinkTo ./config;

  home.activation.tmuxHostConf = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    mkdir -p ~/.config/tmux/styles
    cat > ~/.config/tmux/styles/host.conf << 'EOF'
    # Generated by modules/home/tmux, but can be edited live
    # Set theme.tmux to persist on host
    set -g @host_status_bg '${host.theme.tmux.bg}' # inactive/active
    set -g @host_pane_style '${host.theme.tmux.pane}' # subtle/chunky
    set -g @host_pane_border_style '${host.theme.tmux.border}' # all/none
    EOF
  '';
}
