#!/bin/sh -e

GREEN='\033[1;32m'
YELLOW='\033[1;33m'
RED='\033[1;31m'
NC='\033[0m'

SYSTEM_TYPE="$(hostname)"

export NIXPKGS_ALLOW_UNFREE=1

echo "${YELLOW}Switching home-manager configuration...${NC}"
nix run home-manager -- switch --flake .#${SYSTEM_TYPE} $@

echo "${GREEN}Home-manager switch complete!${NC}"
