#!/bin/sh

# setup ls (note: not POSIX)

# Wow holy fucking shit you're parsing the output of ls? How careless are you?
#
# The ls here without a sort is good enough, but we pipe it into a stable sort,
# sorting on the colored file names from LS_COLORS. This causes the files in our
# directory to show up grouped by file type, alphabetically. It's hacky yeah,
# but it looks good.
#
# shellcheck disable=SC2012
ll() {
        ls -AlGFh --group-directories-first --color "$@" | sort -s -k8,8
}

# SSH doesn't really support XDG config paths, so these are workarounds
# See https://wiki.archlinux.org/index.php/XDG_Base_Directory
alias ssh='ssh -F ~/.config/ssh/config'
alias scp='scp -F ~/.config/ssh/config'

alias l='ll'

# gotta stay safe
alias rm='rm -i'

alias k='kubectl'

# better less
# N line numbers
# F quit if one screen
# RX render escape chars
alias less='less -NFRX'

alias tree='tree --dirsfirst'
