---
title: Andrey Kaipov
baseURL: https://kaipov.com
theme: leekh

params:
  resume: /resume.pdf
  calendar: https://calendly.com/kaipov/call
  favicon: /images/face-flipped.png
  profiles:
  - name: GitHub
    url: https://github.com/andreykaipov
  - name: Twitter
    url: https://twitter.com/andreykaipov
  - name: LinkedIn
    url: https://linkedin.com/in/kaipov

disableKinds:
- taxonomy
- term
- RSS
- sitemap
