# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
locals {
  secrets = {
    for e in one(data.onepassword_item.secrets.section).field :
    e.label => e.value
  }
}

data "onepassword_vault" "vault" {
  name = "github"
}

data "onepassword_item" "secrets" {
  vault = data.onepassword_vault.vault.uuid
  title = "setup.self"
}
