---
name: main

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: wtfjoke/setup-tectonic@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Run Tectonic
      run: ./scripts/build.sh
    - name: Upload PDF
      uses: actions/upload-artifact@v2
      with:
        name: resume # it'll be zipped :(
        path: out/resume.pdf
