---
name: infra

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths: [infra/**, resume/**]

env:
  terragrunt_version: 0.35.4
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  TF_BACKEND_USERNAME: ${{ secrets.TF_BACKEND_USERNAME }}
  TF_BACKEND_PASSWORD: ${{ secrets.TF_BACKEND_PASSWORD }}

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
    - uses: actions/checkout@v2
    - name: Setup Terragrunt
      uses: autero1/action-terragrunt@v1.1.1
      with:
        terragrunt_version: ${{ env.terragrunt_version }}
    - run: terragrunt --version
    - run: curl -v https://tf.kaipov.com/self/infra/tfstate
    - run: make infra/tfstate plan
    - run: make infra/kaipov.com plan
