---
name: resume

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  tectonic_version: 0.4.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/Tectonic
        key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
        restore-keys: |
          ${{ runner.os }}-tectonic-
    - name: Download Tectonic
      uses: wtfjoke/setup-tectonic@main
      with:
        tectonic-version: ${{ env.tectonic_version }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build our resume
      id: build
      run: |
        ./scripts/resume.build.sh
        mv resume.pdf site/static
        echo "::set-output name=msg::gh-actions: add resume.pdf"
    - name: Push that bitch up
      uses: EndBug/add-and-commit@v7
      if: ${{ success() && steps.build.outputs.msg != '' }}
      with:
        add: site/static
        push: true
        author_name: GitHub Actions
        author_email: 41898282+github-actions[bot]@users.noreply.github.com
        message: ${{ steps.build.outputs.msg }}
