---
name: resume

on:
  push:
    branches: [master]
    paths: [resume/**]

env:
  tectonic_version: 0.4.1
  commit_message_resume: "gh-actions: add resume.pdf"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      pushed: ${{ steps.push.outputs.pushed }}
    steps:
    - uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/Tectonic
        key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
        restore-keys: |
          ${{ runner.os }}-tectonic-
    - name: Download Tectonic
      uses: wtfjoke/setup-tectonic@main
      with:
        tectonic-version: ${{ env.tectonic_version }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build our resume
      id: build
      run: |
        ./scripts/resume.build.sh
        mv resume.pdf site/static
        echo "::set-output name=msg::${{ env.commit_message_resume }}"
    - name: Push that bitch up
      id: push
      uses: EndBug/add-and-commit@v7.1.2
      if: ${{ success() && steps.build.outputs.msg != '' }}
      with:
        add: site/static
        push: true
        message: ${{ steps.build.outputs.msg }}
        author_name: github-actions
        author_email: 41898282+github-actions[bot]@users.noreply.github.com
