{
  inputs,
  pkgs,
  lib,
  host,
  ...
}:

let
  theme = host.theme;
  cs = theme.colorscheme;
  tmux = theme.tmux;
in

{
  home.packages = with pkgs; [
    nodejs # for sidekick.nvim and treesitter
    tree-sitter
    lua
    luarocks
    lua-language-server
    stylua
  ];

  xdg.configFile."nvim" = host.symlinkTo ./.;

  programs.neovim = {
    package = inputs.neovim-nightly.packages.${pkgs.stdenv.hostPlatform.system}.default;
    enable = true;
    defaultEditor = true;
    viAlias = true;
    vimAlias = true;
    withRuby = false;
    withPython3 = false;
    initLua = lib.mkForce ""; # suppress HM-generated init.lua — conflicts with xdg.configFile."nvim" symlink
  };

  home.activation.nvim = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    # Generate host.lua before running nvim headless (it dofile's it on startup)
    cat > ~/.config/nvim/host.lua << 'EOF'
    -- Generated by modules/home/nvim, but can be edited live
    return {
      colorscheme = { '${cs.name}', ${toString cs.lighterShade}, ${lib.boolToString cs.blackBg} },
      tmux = { pane = '${tmux.pane}', border = '${tmux.border}', bg = '${tmux.bg}' },
    }
    EOF

    # new line is weird because it sends OSC11 code to tmux
    # ^[Ptmux;^[^[]11;#3d2520^[\^[\
    # over stderr, it shows up as a new line
    printf "installing nvim plugins... "
    date +%s > "$HOME/.local/share/nvim/color-seed"
    PATH="${pkgs.git}/bin:${pkgs.openssh}/bin:${pkgs.tmux}/bin:$PATH" ${
      inputs.neovim-nightly.packages.${pkgs.stdenv.hostPlatform.system}.default
    }/bin/nvim --headless +'lua MiniDeps.snap_load()' +qa 2>&1
  '';
}
