-- User Config
-- host.lua is generated by modules/home/nvim from host.theme
local theme = dofile(vim.fn.stdpath('config') .. '/host.lua')

-- Must be set before colors.lua runs — headless has no terminal to auto-detect
-- from, so without this, highlight groups return 'default' instead of hex
-- colors, and the tmux/wezterm color caches never get written. This way, the
-- headless nvim instance in our activation script can set the colorscheme for
-- our entire terminal during the #switch!
vim.o.termguicolors = true

vim.g.user = {
	leader = ' ',
	scrolloff = 20,
	sidebar_width = 30,
	theme = theme,
}

-- Bootstrap mini.nvim
if not require('custom.minideps').setup() then
	vim.notify('Failed to bootstrap mini.nvim', vim.log.levels.ERROR)
	return
end

-- Load custom modules
require('custom.basics').setup()
require('custom.navigation').setup()
require('custom.autosave').setup()
require('custom.colors').setup()
require('custom.editing').setup()
require('custom.guides').setup()
require('custom.git').setup()
require('custom.pi').setup()
require('custom.buffers').setup()
require('custom.nvim-tree').setup()
require('custom.picker').setup()
require('custom.statusline').setup()
require('custom.treesitter').setup()
require('custom.lsp').setup()
require('custom.tidal').setup()

-- Setup MiniNotify after all modules so it doesn't swallow MiniDeps install
-- logs during headless bootstrap (mini.notify is part of mini.nvim, so it
-- doesn't need a MiniDeps.add and has no install log of its own).
require('mini.notify').setup({
	lsp_progress = { enable = false },
})

-- Open notification history in a buffer that doesn't interfere with our buffer logic
vim.keymap.set('n', '<leader>nn', function()
	MiniNotify.show_history()
	vim.bo.buftype = ''
	vim.bo.bufhidden = 'wipe'
	vim.bo.modified = false
end, { desc = 'Notification history' })

-- Reload colorscheme and custom highlights without restarting
vim.keymap.set('n', '<leader>cc', function()
	package.loaded['custom.colors'] = nil
	require('custom.colors').setup({ reseed = true })
end, { desc = 'Reload colorscheme' })

-- Reload entire lua config without restarting
vim.keymap.set('n', '<leader>cr', function()
	for name, _ in pairs(package.loaded) do
		if name:match('^custom%.') then
			package.loaded[name] = nil
		end
	end
	dofile(vim.fn.stdpath('config') .. '/init.lua')
	vim.notify('Config reloaded', vim.log.levels.INFO)
end, { desc = 'Reload config' })

if #vim.api.nvim_list_uis() == 0 then
	print('')
end
